-- ⚠️ 此文件已过时，无法与 traffic-core/src/classifier.rs 同步
--
-- 应用分类逻辑现在完全由 Rust 代码中的 RULES 静态数组定义
-- (traffic-core/src/classifier.rs:55-372)。
-- 如需重新分类已有数据，请重新插入数据而非使用 ALTER TABLE UPDATE。
-- ALTER TABLE UPDATE 的 app_id 映射与当前分类器不一致。
